"""2014-09-26T23:42:10Z

Revision ID: 2360ddba87d
Revises: 5378709620d8
Create Date: 2014-09-26 19:42:11.349716

"""

# revision identifiers, used by Alembic.
revision = '2360ddba87d'
down_revision = '5378709620d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('to_produce', sa.String(length=60), nullable=False),
    sa.Column('village_symbol', sa.String(length=15), nullable=False),
    sa.Column('collection_month', sa.Integer(), nullable=False),
    sa.Column('collection_year', sa.Integer(), nullable=False),
    sa.Column('sample_type', sa.String(length=15), nullable=False),
    sa.Column('tube_number', sa.Integer(), nullable=False),
    sa.Column('date_of_request', sa.DateTime(), nullable=False),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('new_building', sa.String(length=5), nullable=False),
    sa.Column('new_room', sa.Integer(), nullable=False),
    sa.Column('new_cryo', sa.String(length=30), nullable=False),
    sa.Column('sample_status', sa.String(length=15), nullable=False),
    sa.Column('passed_validation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'uploads', sa.Column('processed', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'uploads', 'processed')
    op.drop_table('checkout_requests')
    ### end Alembic commands ###
