"""empty message

Revision ID: 3644f9c96e20
Revises: 55682b41093b
Create Date: 2014-09-28 17:22:44.591063

"""

# revision identifiers, used by Alembic.
revision = '3644f9c96e20'
down_revision = '55682b41093b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
