"""empty message

Revision ID: 4314ad542c9
Revises: 3644f9c96e20
Create Date: 2014-09-28 17:24:36.665185

"""

# revision identifiers, used by Alembic.
revision = '4314ad542c9'
down_revision = '3644f9c96e20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
