"""testing User changed backref from users to user

Revision ID: 5378709620d8
Revises: 37c2e7ada589
Create Date: 2014-09-26 13:21:46.523441

"""

# revision identifiers, used by Alembic.
revision = '5378709620d8'
down_revision = '37c2e7ada589'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
