"""empty message

Revision ID: 55682b41093b
Revises: None
Create Date: 2014-09-28 16:18:26.627683

"""

# revision identifiers, used by Alembic.
revision = '55682b41093b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('pi_name', sa.String(length=80), nullable=False),
    sa.Column('pi_email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_at')
    )
    op.create_table('checkout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('to_produce', sa.String(length=60), nullable=False),
    sa.Column('village_symbol', sa.String(length=15), nullable=False),
    sa.Column('collection_month', sa.Integer(), nullable=False),
    sa.Column('collection_year', sa.Integer(), nullable=False),
    sa.Column('tissue_type', sa.String(length=15), nullable=False),
    sa.Column('tube_number', sa.Integer(), nullable=False),
    sa.Column('date_of_request', sa.DateTime(), nullable=False),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('new_building', sa.String(length=5), nullable=False),
    sa.Column('new_room', sa.String(length=8), nullable=False),
    sa.Column('new_cryo', sa.String(length=30), nullable=False),
    sa.Column('sample_status', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('checkout_requests')
    op.drop_table('uploads')
    op.drop_table('users')
    ### end Alembic commands ###
