"""added Upload table model

Revision ID: 10c1dcb1064b
Revises: 53816cb45545
Create Date: 2014-09-26 09:48:07.987905

"""

# revision identifiers, used by Alembic.
revision = '10c1dcb1064b'
down_revision = '53816cb45545'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    ### end Alembic commands ###
