"""Sun Sep 28 16:02:24 EDT 2014

Revision ID: 144cab478237
Revises: 2360ddba87d
Create Date: 2014-09-28 16:02:24.834091

"""

# revision identifiers, used by Alembic.
revision = '144cab478237'
down_revision = '2360ddba87d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_requests', sa.Column('tissue_type', sa.String(length=15), default="OTHER", nullable=False))
    op.drop_column('checkout_requests', 'sample_type')
    op.drop_column('checkout_requests', 'passed_validation')
    op.add_column('uploads', sa.Column('validated', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'validated')
    op.add_column('checkout_requests', sa.Column('passed_validation', sa.BOOLEAN(), nullable=True))
    op.add_column('checkout_requests', sa.Column('sample_type', sa.VARCHAR(length=15), nullable=False))
    op.drop_column('checkout_requests', 'tissue_type')
    ### end Alembic commands ###
