"""testing User change 2

Revision ID: 37c2e7ada589
Revises: 10c1dcb1064b
Create Date: 2014-09-26 10:55:35.041197

"""

# revision identifiers, used by Alembic.
revision = '37c2e7ada589'
down_revision = '10c1dcb1064b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('save_location', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'save_location')
    ### end Alembic commands ###
